"""The C# text every generated file is built out of: the escapes, the header and the two
literals more than one renderer writes.

Nothing here reads the map. It is the layer below the renderers (entries.py, registry.py,
contracts.py, correspondence.py), and it is deliberately dull: the engine's gate compares every
`*.g.cs` byte for byte against a fresh regeneration, so a change to an escape or to a line of the
header is a change to every engine's source, and belongs where it can be seen on its own.
"""


def cs_string(text):
    out = ['"']
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ch in "\u2028\u2029":
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def xml_text(text):
    return " ".join(str(text).split()).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


HEADER = ("// <auto-generated>\n"
          "//   Generated by rules-factory tools/factory from {package}{version}.\n"
          "//   Every *.g.cs file is rewritten by `factory produce`; edit hand-written files instead.\n"
          "// </auto-generated>\n"
          "#nullable enable\n\n")


ASSERTED_BY_MEMBER = (
    "    /// <summary>\n"
    "    /// Who the corpus lets assert this entry, the map's <c>assertedBy</c> (rules-factory decision 0025): the\n"
    "    /// corpus's own words, or <c>caller</c> where the corpus names nobody. Empty on an entry that is not\n"
    "    /// <c>kind: assertion</c>. An engine checks an assertion's attribution against these, not its own reading.\n"
    "    /// </summary>\n"
    "    public ImmutableArray<string> AssertedBy { get; init; } = [];\n\n")


def value_record_equality(record, scalar_members, collection_members):
    """Value equality for a sealed record whose collections must compare element by element.

    C# records otherwise compare a collection member through EqualityComparer<T>.Default, which
    makes ImmutableArray and interface-typed collections compare their backing objects. Keeping
    this renderer about collection *members*, rather than ImmutableArray specifically, gives every
    record renderer one shape to use when it owns sequence-valued state.
    """
    comparisons = [f"{member} == other.{member}" for member in scalar_members]
    comparisons.extend(f"{member}.SequenceEqual(other.{member})" for member in collection_members)
    equality = " &&\n        ".join(comparisons)
    lines = [
        "    /// <inheritdoc/>\n",
        f"    public bool Equals({record}? other) =>\n",
        "        other is not null &&\n",
        f"        {equality};\n\n",
        "    /// <inheritdoc/>\n",
        "    public override int GetHashCode()\n",
        "    {\n",
        "        var hash = new HashCode();\n",
    ]
    for member in scalar_members:
        lines.append(f"        hash.Add({member});\n")
    for member in collection_members:
        lines.extend([
            f"        hash.Add({member}.Count());\n",
            f"        foreach (var item in {member})\n",
            "        {\n",
            "            hash.Add(item);\n",
            "        }\n",
        ])
    lines.extend([
        "        return hash.ToHashCode();\n",
        "    }\n\n",
    ])
    return "".join(lines)


def asserted_by_init(entry):
    """The object initializer carrying `assertedBy` (0025), or nothing on an entry without one.

    An init property rather than a positional parameter, so the records' constructors and
    deconstructors, which an engine's own code may call, do not change.
    """
    names = entry.get("assertedBy")
    if not isinstance(names, list) or not names:
        return ""
    return f" {{ AssertedBy = [{', '.join(cs_string(name) for name in names)}] }}"


def locator_cs(locator):
    return f"new SourceLocator({cs_string(locator['sourceId'])}, {cs_string(locator['citation'])})"
