"""Every version the factory pins, and the one generated file MSBuild reads.

`RulesFactory.Packages.g.props` holds what MSBuild reads that the inputs decide: the exact
version pins of RulesKernel and the map package, and the map's PackageReference (conditioned
on the engine project, so the test project does not take it). When the corpus declares
`randomness: seeded` (decision 0019) it also pins RulesKernel.Randomness at the kernel's version,
RulesKernel.Analyzers always,
and references nothing: whether and where to draw is the engine's to write, and the pin only
means that when it does, the version is the kernel's. Under `none` there is no pin. Directory.Packages.props imports
it, and keeps only the central-package-management switches and the test packages, which an
engine may bump on its own. Because the pins now have one home, `produce` refuses, before
writing anything, an engine whose own MSBuild files pin the kernel or the map again, reference a
map package themselves, or whose Directory.Packages.props does not import the generated file.
"""
import os
import re

import csharp
import semantics

KERNEL_VERSION = "1.0.0"


# The SDK rules-kernel pins (its global.json), so a produced engine builds with the kernel's
# toolchain. This is the kernel's pin, not this machine's: never substitute a local SDK here.
SDK_VERSION = "10.0.112"
TEST_PACKAGES = (
    ("Microsoft.NET.Test.Sdk", "17.11.1"),
    ("xunit", "2.9.2"),
    ("xunit.runner.visualstudio", "2.8.2"),
)


PACKAGES_PROPS = "RulesFactory.Packages.g.props"


# Decision 0019: the corpus's `randomness`, carried from its manifest by intake.
RANDOMNESS_PACKAGE = "RulesKernel.Randomness"


# The kernel's compile-time determinism diagnostics (RK0001-RK0005, RK0007), pinned at the kernel's
# version like everything else the kernel ships. Referenced by the engine project alone, the way the
# map package is: a build asset, never a reference, and never part of the test project's graph.
ANALYZERS_PACKAGE = "RulesKernel.Analyzers"
RANDOMNESS = ("none", "seeded")


def packages_props(model):
    """The pins and the map reference: everything MSBuild reads that the factory's inputs decide."""
    if model.randomness not in RANDOMNESS:
        raise semantics.GenerationError(f"the corpus's randomness is {model.randomness!r}, not one of {', '.join(RANDOMNESS)} "
                              f"(decision 0019), so whether to pin {RANDOMNESS_PACKAGE} is undecided")
    randomness = "" if model.randomness == "none" else (
        "    <!-- The corpus declares randomness: seeded (rules-factory decision 0019), so the engine may\n"
        "         reference RulesKernel.Randomness. It is pinned here, at the kernel's version, and the\n"
        "         factory references it nowhere: whether and where to draw is the engine's code. -->\n"
        f'    <PackageVersion Include="{RANDOMNESS_PACKAGE}" Version="{KERNEL_VERSION}" />\n')
    return (
        "<Project>\n\n"
        "  <!-- <auto-generated>\n"
        f"       Generated by rules-factory tools/factory from {csharp.xml_text(model.named)}.\n"
        "       Rewritten by every `factory produce`; recorded in provenance.json. Do not edit.\n"
        "       </auto-generated> -->\n\n"
        "  <ItemGroup>\n"
        "    <!-- The kernel is referenced, never copied. -->\n"
        f'    <PackageVersion Include="RulesKernel" Version="{KERNEL_VERSION}" />\n'
        "    <!-- The kernel's determinism analyzers, at the kernel's version. An engine that copied a\n"
        "         list of forbidden constructs into itself would diverge from every other engine's copy,\n"
        "         which is what the kernel exists to end (rules-factory decision 0029). -->\n"
        f'    <PackageVersion Include="{ANALYZERS_PACKAGE}" Version="{KERNEL_VERSION}" />\n'
        f"{randomness}"
        "    <!-- Each map is referenced, never copied (rules-factory decision 0015), at an exact\n"
        "         version. The engine's own build facts live in overlay/. An engine composed of\n"
        "         several maps references every one of them (0067). -->\n"
        + "".join(f'    <PackageVersion Include="{package}" Version="[{version}]" />\n'
                  for package, version in model.packages)
        + "  </ItemGroup>\n\n"
        + "  <!-- The map(s) this engine is built from, referenced by the engine project only. Each\n"
        "       carries no assemblies; its build props add one RulesFactoryMap item naming the\n"
        "       restored map, manifest and checker. -->\n"
        f"  <ItemGroup Condition=\"'$(MSBuildProjectName)' == '{model.name}'\">\n"
        + "".join(f'    <PackageReference Include="{package}" PrivateAssets="all" />\n'
                  for package, _ in model.packages)
        + "    <!-- The analyzers, on the engine project only: a determinism defect in the rules is a build\n"
        "         error, and a test that fakes a clock or iterates a set is not the engine doing it.\n"
        "         .editorconfig states each severity rather than leaving it to the package's defaults. -->\n"
        f'    <PackageReference Include="{ANALYZERS_PACKAGE}" PrivateAssets="all" />\n'
        "  </ItemGroup>\n\n"
        "</Project>\n")


MSBUILD_FILES = (".props", ".targets", ".csproj")
ENGINE_BUILD_SKIP = {"bin", "obj", ".git", ".vs", "corpus", "backlog", "Generated"}


def refuse_split_pins(model, out):
    """Refuse an engine whose own MSBuild files would contradict the generated pins.

    The kernel and map versions, and the reference to the map package, have exactly one home:
    PACKAGES_PROPS, rewritten every run. An engine-owned file that pins either package again, or
    references a map package itself, or a Directory.Packages.props that does not import the
    generated file (an engine scaffolded before the pins moved there), would let the build use a
    version provenance does not name. Refused before anything is written, rather than repaired:
    those files are the engine's, and the factory does not edit them.
    """
    pinned = ({"RulesKernel"} | {package for package, _ in model.packages}
              | ({RANDOMNESS_PACKAGE} if model.randomness == "seeded" else set()))
    found = []
    for directory, dirs, names in os.walk(out):
        dirs[:] = sorted(d for d in dirs if d not in ENGINE_BUILD_SKIP)
        for file_name in sorted(names):
            if not file_name.endswith(MSBUILD_FILES) or file_name == PACKAGES_PROPS:
                continue
            path = os.path.join(directory, file_name)
            relative = os.path.relpath(path, out).replace(os.sep, "/")
            try:
                with open(path, encoding="utf-8") as handle:
                    text = handle.read()
            except (OSError, UnicodeDecodeError) as error:
                raise semantics.GenerationError(f"cannot read {path}: {error}")
            for element, package in re.findall(r'<(PackageVersion|PackageReference)\b[^>]*?\bInclude="([^"]+)"', text):
                if element == "PackageVersion" and package in pinned:
                    found.append(f"{relative} pins {package}")
                elif element == "PackageReference" and (
                        package in {name for name, _ in model.packages}
                        or package.startswith("RulesFactory.Maps.")):
                    found.append(f"{relative} references the map package {package}")
            if re.search(r'\bVersionOverride="', text):
                for package in re.findall(r'<PackageReference\b[^>]*?\bInclude="([^"]+)"[^>]*?\bVersionOverride="', text):
                    if package in pinned:
                        found.append(f"{relative} overrides the version of {package}")
            if relative == "Directory.Packages.props" and PACKAGES_PROPS not in text:
                found.append(f"{relative} does not import {PACKAGES_PROPS}")
    if found:
        raise semantics.GenerationError("the engine's own build files would pin a different kernel or map than the one "
                              f"generated ({'; '.join(found)}); the pins and the map reference belong in "
                              f"{PACKAGES_PROPS}, which every produce rewrites, so remove them from those files")
