#!/usr/bin/env bash
# re-produce.sh -- re-run `factory produce` on this engine, from the factory commit the record names.
#
#   tools/re-produce.sh                 re-produce this engine, gate and all
#   tools/re-produce.sh --dry-run       print the produce it would run, and change nothing
#   tools/re-produce.sh --resolve-record  take one side of a merge-conflicted provenance.json first
#   tools/re-produce.sh --no-verify     (and any other argument) passed through to produce
#
# It reads the repository root from the record too (0069), so an embedded engine re-produces
# with no arguments of its own. An explicit --repo-root wins, which is how a moved engine is
# re-produced at its new place.
#
# Emitted by rules-factory as a managed file (decision 0029).
#
# **An overlay edit is finished by a re-produce.** `provenance.json` is a generated file
# (decision 0018): `factory produce` is its only author, and nothing in a produced engine can
# refresh it. The gate's own regeneration step refreshes the generated C# and nothing else, so
# after an overlay change the record still hashes the old generated bytes, and still hashes the
# overlay as it was before the edit. `scripts/engine-gate.py provenance` compares those hashes --
# `buildInputs/overlay/<entry id>.json`, as a set, so a file added or removed is caught as loudly as
# one edited -- and fails while they are stale, naming this script.
#
# **Why a script and not a paragraph.** The procedure is: clone rules-factory at the commit the
# record names, and run produce with the package, corpus, name and output this engine's record
# gives. Written as prose it is four lookups and a clone that an operator has to get right, and it
# has a trap in it: cloning the factory's `main` instead of the recorded commit re-emits the gate,
# the rails and the vendored generator from a factory nobody asked for, and folds that into an
# implementation pull request where no reviewer is looking for it. So the clone below is pinned to
# `factory.commit`, and moving this engine to a newer factory stays a deliberate act with its own
# issue.
#
# **A merge conflict in the record is not a decision to make (#252).** Since the overlay became a
# directory, `provenance.json` is the one file two entry branches cut from the same commit still
# conflict in, and a file holding conflict markers is not JSON -- so the one command that recomputes
# every hash in it could not run until somebody had already resolved it by hand, and nothing said
# so. There is nothing in the record to resolve: a re-produce overwrites the whole of it, so both
# sides are discarded whichever is kept, and neither is more right than the other. So this script
# recognises the conflict and says exactly that, and `--resolve-record` takes a side and re-produces
# over it, which makes the recovery one command.
#
# It is a flag and not the default because taking a side in somebody's merge is an act even when the
# bytes are about to be overwritten: it is asked for once, here, rather than discovered afterwards.
# The side taken is `--ours` -- the branch you are on -- for a reason beyond arbitrariness: the check
# further down compares the working tree's `factory.commit` with the committed record's, and `--ours`
# is the side that is already `HEAD`'s.
#
# **It makes no commit.** `produce` makes none by design, and neither does this. What it changes is
# yours to read and stage. `--resolve-record` is the one exception, and only for the record: git
# has no way to mark a path resolved without staging it, so that one path is staged and said aloud.
#
# Standard library tools only: bash, git and python3.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

GIT="${RULES_ENGINE_GIT:-git}"
PYTHON="${RULES_ENGINE_PYTHON:-python3}"
RECORD="provenance.json"
# provenance.json names the factory's commit, not where the factory lives, so the URL is a constant
# here. If the record ever gains a `factory.repository`, the read below prefers it and this becomes
# the fallback. $RULES_ENGINE_FACTORY_REPO overrides both, for a mirror or an offline clone.
FACTORY_REPO_DEFAULT="https://github.com/brandonifco/rules-factory.git"

DRY_RUN=0
RESOLVE_RECORD=0
EXTRA=()

die() { printf 'error: %s\n' "$1" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    --resolve-record) RESOLVE_RECORD=1; shift ;;
    -h|--help) sed -n '2,8p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) EXTRA+=("$1"); shift ;;
  esac
done

[[ -f "$RECORD" ]] || die "$RECORD is not here; run this from a produced engine"

# The markers a merge leaves in a file it could not merge, at the start of a line. All three are
# required, so a record that is merely broken keeps its own message and is not called a conflict.
# (`|||||||` appears as well under merge.conflictStyle=diff3; it is not required here.)
record_is_conflicted() {
  grep -q '^<<<<<<<' "$RECORD" && grep -q '^=======' "$RECORD" && grep -q '^>>>>>>>' "$RECORD"
}

if record_is_conflicted; then
  # git's index is what decides whether a side can be taken: `--ours` needs the path unmerged
  # there. A record holding markers with nothing unmerged behind it was staged, or committed, in
  # that state, and then the committed record is the only side there is.
  UNMERGED=""
  if "$GIT" rev-parse --verify -q HEAD >/dev/null 2>&1; then
    UNMERGED="$("$GIT" ls-files -u -- "$RECORD" 2>/dev/null || true)"
    if [[ -n "$UNMERGED" ]]; then
      BY_HAND="git checkout --ours -- $RECORD && git add $RECORD"
    else
      BY_HAND="git checkout HEAD -- $RECORD"
    fi
  else
    BY_HAND=""
  fi

  # `--dry-run` changes nothing, and that includes somebody's index: it reports the conflict and
  # the command, the same as a run without the flag.
  if [[ "$RESOLVE_RECORD" -eq 0 || "$DRY_RUN" -eq 1 ]]; then
    [[ -n "$BY_HAND" ]] || die "$RECORD is in a merge conflict, and this is not a git checkout with a
       committed $RECORD, so there is no side to take. Every hash in the record is recomputed by a
       re-produce, so either side is equally good -- put one of them in place and run this again."
    die "$RECORD is in a merge conflict, so this script cannot read what to re-produce. Neither side
       of it is the one to keep: every hash in the record is about to be recomputed, so either side
       is equally good, and that is why this is not yours to decide. One command settles it --
       \`tools/re-produce.sh --resolve-record\`, which takes one side and re-produces over it. By
       hand it is \`$BY_HAND\`, then this script again."
  fi

  [[ -n "$BY_HAND" ]] || die "$RECORD is in a merge conflict and this is not a git checkout with a
       committed $RECORD, so --resolve-record has no side to take."
  if [[ -n "$UNMERGED" ]]; then
    SIDE="ours, the branch you are on"
  else
    SIDE="the committed record, which is the only side git still has"
  fi
  printf 'note: %s is in a merge conflict. Every hash in it is about to be recomputed, so either\n' "$RECORD" >&2
  printf '      side is equally good; --resolve-record takes %s\n      and re-produces over it (%s).\n' \
         "$SIDE" "$BY_HAND" >&2
  if [[ -n "$UNMERGED" ]]; then
    "$GIT" checkout --ours -- "$RECORD" || die "could not take our side of $RECORD (\`$BY_HAND\`)"
    "$GIT" add -- "$RECORD" || die "could not stage $RECORD, so git would still call it unmerged"
  else
    "$GIT" checkout HEAD -- "$RECORD" || die "could not restore the committed $RECORD (\`$BY_HAND\`)"
  fi
  ! record_is_conflicted || die "$RECORD still holds conflict markers after \`$BY_HAND\`, so the side
       that was taken is itself a conflicted file. Nothing here can choose for you now: resolve it
       and run this again."
fi

# Everything produce needs, read from the record in one pass so a malformed field is named once.
# The corpora are the record's `corpora` (0039, 0070): a map may cite several, and produce is given
# one --corpus for each. The principal -- the one the map's envelope names -- goes first, then the
# rest in the record's own order (sorted by sourceId), so the same record always makes the same
# produce. A record that does not say which corpus is the principal, or names a corpus twice, or
# names one that is not a file under corpus/, does not say what to re-produce and is refused.
FIELDS="$("$PYTHON" - "$RECORD" "$FACTORY_REPO_DEFAULT" <<'PY'
import json, sys
try:
    with open(sys.argv[1], encoding="utf-8") as handle:
        record = json.load(handle)
except (OSError, ValueError) as error:
    sys.exit(f"{sys.argv[1]} cannot be read ({error})")
factory = record.get("factory") or {}
commit = factory.get("commit")
if not (isinstance(commit, str) and len(commit) == 40 and all(c in "0123456789abcdef" for c in commit)):
    sys.exit(f"{sys.argv[1]} names no factory.commit to re-produce from (got {commit!r})")
# Every package the engine is composed of, in the record's own order (0067). One is the ordinary
# case; a composed engine is re-produced from all of them or from none.
packages = [m for m in record.get("maps") or [] if isinstance(m, dict)]
name = (record.get("engine") or {}).get("name")
corpora = [item for item in record.get("corpora") or [] if isinstance(item, dict)]
if not corpora:
    sys.exit(f"{sys.argv[1]} names no corpus under `corpora`; a record written before "
             f"provenanceFormat 5 names one under `corpus` and this script cannot re-produce from it")
paths = []
for position, corpus in enumerate(corpora):
    path = corpus.get("path")
    if not (isinstance(path, str) and path.startswith("corpus/") and len(path) > len("corpus/")
            and path.isprintable()):
        sys.exit(f"{sys.argv[1]} names no corpus/ file at corpora[{position}].path (got {path!r})")
    if path in paths:
        sys.exit(f"{sys.argv[1]} names {path} more than once under `corpora`")
    paths.append(path)
principals = [c["path"] for c in corpora if c.get("principal") is True]
if len(principals) != 1:
    sys.exit(f"{sys.argv[1]} marks {len(principals)} corpora as principal; exactly one is the corpus "
             f"the map names, and produce takes it first")
ordered = principals + [p for p in paths if p != principals[0]]
if not packages:
    sys.exit(f"{sys.argv[1]} names no map package under `maps`; a record written before "
             f"provenanceFormat 7 names one under `map` and this script cannot re-produce from it")
for position, package in enumerate(packages):
    for label in ("packageId", "version"):
        if not package.get(label):
            sys.exit(f"{sys.argv[1]} names no maps[{position}].{label}")
if not name:
    sys.exit(f"{sys.argv[1]} names no engine.name")
print(commit)
print(" ".join(f"{m['packageId']}@{m['version']}" for m in packages))
print(name)
print(factory.get("repository") or sys.argv[2])
print("dirty" if factory.get("dirty") else "clean")
# Where the engine sits inside its repository (0069). Absent in a record written before
# provenanceFormat 9, and empty for an engine that is its own repository root -- both of which
# mean the same thing here, and both of which are the standalone case.
print((record.get("repository") or {}).get("enginePath") or "")
# The corpora come last, one to a line, principal first: there is a variable number of them.
for path in ordered:
    print(path)
PY
)" || die "the record does not say what to re-produce (above)"

mapfile -t FIELD <<<"$FIELDS"
COMMIT="${FIELD[0]}"; read -r -a PACKAGES <<<"${FIELD[1]}"; NAME="${FIELD[2]}"
FACTORY_REPO="${RULES_ENGINE_FACTORY_REPO:-${FIELD[3]}}"; FACTORY_DIRTY="${FIELD[4]}"
ENGINE_PATH="${FIELD[5]:-}"
CORPORA=("${FIELD[@]:6}")

for CORPUS in "${CORPORA[@]}"; do
  [[ -f "$CORPUS" ]] || die "$RECORD names the corpus $CORPUS, which is not in this engine"
done

# A dirty working tree is the normal case here: this is what you run *after* writing your entry's
# overlay file and regenerating, so the overlay and the generated C# are modified by definition,
# and refusing that would refuse the only workflow this script exists for. Hand-written source, tests and build
# inputs are the engine's to change, and produce hashes whatever is on disk, which is what the
# commit that follows will carry.
#
# What genuinely must not be in doubt is the one field this script *obeys*: `factory.commit`
# decides which factory code is about to rewrite the gate, the rails and the vendored generator.
# So the working tree's record is compared with the committed one, on that field alone. A
# re-produce writes back the commit it read, so running this twice before committing is fine; a
# hand edit that points it at another factory is refused by name. Everything else the record holds
# is produce's own output and is expected to differ here.
#
# Two related cases need no rule of their own, because produce already refuses them and says why:
# a modified corpus/ file (intake hashes it against the map's baseline) and a hand-edited managed
# file (ownership.py names it and offers --adopt or --reset).
if "$GIT" rev-parse --verify -q HEAD >/dev/null 2>&1 && "$GIT" ls-files --error-unmatch "$RECORD" >/dev/null 2>&1; then
  COMMITTED_COMMIT="$("$GIT" show "HEAD:./$RECORD" 2>/dev/null | "$PYTHON" -c \
    'import json,sys; print((json.load(sys.stdin).get("factory") or {}).get("commit") or "")' 2>/dev/null || true)"
  if [[ -n "$COMMITTED_COMMIT" && "$COMMITTED_COMMIT" != "$COMMIT" ]]; then
    die "$RECORD in the working tree names factory.commit $COMMIT, and the committed one names
       $COMMITTED_COMMIT. This script checks out the commit the record names, so an uncommitted
       change to that field decides which factory rewrites this engine. Restore it with
       \`git checkout -- $RECORD\`, or commit the move to a new factory deliberately, on its own
       issue, before re-producing."
  fi
else
  printf 'note: this engine is not a git checkout with a committed %s, so the recorded factory\n' "$RECORD" >&2
  printf '      commit could not be compared with a reviewed one.\n' >&2
fi

[[ "$FACTORY_DIRTY" == "clean" ]] || printf 'note: %s records factory.dirty: true, so commit %s is not the whole of the\n      code that produced this engine; this re-produce runs that commit as committed.\n' "$RECORD" "$COMMIT" >&2

# Since 0069 there is a fifth thing produce has to be told, and the record carries it like the rest.
# An embedded engine's workflows and pull request template belong at the repository root, where
# GitHub reads them; a standalone engine's belong beside the engine. Produce refuses to guess between
# the two, and this script exists so that nobody has to answer it by hand -- an operator who gets
# `--repo-root` wrong produces a working engine whose rails are dark, which is the exact failure 0069
# was written about.
#
# The root is the engine directory with the recorded `enginePath` taken off the end, so the two
# always compose back to where this script is running. An explicit `--repo-root` still wins: it is
# how an engine that is being moved is re-produced at its new place.
REPOSITORY_ROOT="$REPO_ROOT"
if [[ -n "$ENGINE_PATH" ]]; then
  SEPARATORS="${ENGINE_PATH//[^\/]/}"
  for (( LEVEL = 0; LEVEL <= ${#SEPARATORS}; LEVEL++ )); do
    REPOSITORY_ROOT="$(dirname "$REPOSITORY_ROOT")"
  done
  [[ "$REPOSITORY_ROOT/$ENGINE_PATH" == "$REPO_ROOT" ]] || die "$RECORD records repository.enginePath
       $ENGINE_PATH, which does not compose back to $REPO_ROOT. The engine has been moved, and
       re-producing it here would write its workflows somewhere nobody has checked. Produce it
       deliberately with an explicit --repo-root, on its own issue."
  # git is the second opinion, and a disagreement means the engine moved between repositories rather
  # than within one. Asked only where there is a checkout to ask.
  if TOP_LEVEL="$("$GIT" rev-parse --path-format=absolute --show-toplevel 2>/dev/null)" \
     && [[ -n "$TOP_LEVEL" && "$TOP_LEVEL" != "$REPOSITORY_ROOT" ]]; then
    die "$RECORD puts this engine at $ENGINE_PATH inside $REPOSITORY_ROOT, and git reports the
       repository root as $TOP_LEVEL. One of the two is wrong, and this script will not pick. Re-
       produce with an explicit --repo-root once you know which."
  fi
fi

ROOT_ARGS=(--repo-root "$REPOSITORY_ROOT")
for ARGUMENT in ${EXTRA[@]+"${EXTRA[@]}"}; do
  [[ "$ARGUMENT" == "--repo-root" || "$ARGUMENT" == --repo-root=* ]] && ROOT_ARGS=()
done

PACKAGE_ARGS=()
for PACKAGE in "${PACKAGES[@]}"; do PACKAGE_ARGS+=(--package "$PACKAGE"); done
CORPUS_ARGS=()
for CORPUS in "${CORPORA[@]}"; do CORPUS_ARGS+=(--corpus "$REPO_ROOT/$CORPUS"); done
PRODUCE=("$PYTHON" "<factory>/tools/factory" produce "${PACKAGE_ARGS[@]}" "${CORPUS_ARGS[@]}"
         --name "$NAME" --out "$REPO_ROOT" ${ROOT_ARGS[@]+"${ROOT_ARGS[@]}"}
         ${EXTRA[@]+"${EXTRA[@]}"})

printf 'factory   %s at %s\n' "$FACTORY_REPO" "$COMMIT"
printf 'package   %s\n' "${PACKAGES[*]}"
printf 'corpus    %s\n' "${CORPORA[*]}"
printf 'engine    %s (%s)\n' "$NAME" "$REPO_ROOT"
if [[ -n "$ENGINE_PATH" ]]; then
  printf 'repo      %s (the engine is embedded at %s/)\n' "$REPOSITORY_ROOT" "$ENGINE_PATH"
fi
printf 'produce   %s\n' "${PRODUCE[*]}"

if [[ "$DRY_RUN" -eq 1 ]]; then
  printf '\n--dry-run: nothing was cloned, produced or committed.\n'
  exit 0
fi

CLONE="$(mktemp -d)"
trap 'rm -rf "$CLONE"' EXIT

# Fetched by SHA at a depth of one, so no factory history is downloaded and `main` is never
# checked out. A server that refuses a by-SHA fetch (uploadpack.allowReachableSHA1InWant off)
# falls back to a full clone, which still checks out the recorded commit and never `main`.
printf '\ncloning the factory at %s\n' "$COMMIT"
"$GIT" init -q "$CLONE"
"$GIT" -C "$CLONE" remote add origin "$FACTORY_REPO"
if "$GIT" -C "$CLONE" fetch -q --depth 1 origin "$COMMIT" 2>/dev/null; then
  "$GIT" -C "$CLONE" checkout -q FETCH_HEAD
  # Best effort, and never fatal: provenance names the factory's version from a `factory/vX.Y.Z`
  # tag on that commit, so a clone without tags would record 0.0.0-dev+<sha> for a tagged release.
  "$GIT" -C "$CLONE" fetch -q --depth 1 origin "+refs/tags/*:refs/tags/*" 2>/dev/null || true
else
  rm -rf "$CLONE"
  "$GIT" clone -q "$FACTORY_REPO" "$CLONE" || die "could not clone $FACTORY_REPO"
  "$GIT" -C "$CLONE" checkout -q "$COMMIT" || die "$FACTORY_REPO has no commit $COMMIT"
fi

PRODUCE[1]="$CLONE/tools/factory"
printf 'running   %s\n\n' "${PRODUCE[*]}"
"${PRODUCE[@]}"

printf '\nre-produced. No commit was made: read what changed (provenance.json and the generated\n'
printf 'files) and stage it with the rest of your change.\n'
